# Generated by Django 5.2.17 on 2026-09-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0, help_text='Contador de acessos, usado no widget "Mais Lidas".', verbose_name='Visualizações'),
        ),
    ]
